Revert 286504 "Fix typos in num_failures_by_type for json results."
Suspected cause of results_viewer_unittest.testBasic timeout:

http://build.chromium.org/p/chromium.win/builders/Vista%20Tests%20%282%29/builds/44045
TimeoutException: Timed out while waiting 120s for IsJavaScriptExpressionTrue.

> Fix typos in num_failures_by_type for json results.
> 
> This changes a few occurrences of "Failure" -> "FAIL" and "Pass" -> "PASS"
> to conform to the doc format. The existing data is not actually being
> used yet, but the flakiness dashboard needs the correct values.
> 
> Also fix a typo in run_mojo_python_tests that was preventing us from
> running individual tests on the command line.
> 
> R=ojan@chromium.org, viettrungluu@chromium.org, grt@chromium.org
> 
> Review URL: https://codereview.chromium.org/429013004

TBR=dpranke@chromium.org

Review URL: https://codereview.chromium.org/430913003

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 29f6350200a18c1c4ca5c20aa60f13b87666e7b0