[Telemetry] Set same settings on memory cache http server that WPR sets.
It looks like the error that the windows dom_perf tests are hitting could be
caused by improperly closing the socket, which this might fix.

error: [Errno 10053] An established connection was aborted by the software in your host machine

BUG=335624

Review URL: https://codereview.chromium.org/259623003

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8d72993ee340712ec3f789806153675a19f37767