Fix incorrect re-raise in android_browser_finder.py.
I came across this while sheriffing:

Traceback (most recent call last):
  RunBenchmark at tools/telemetry/telemetry/.../story_runner.py:294
    Run(pt, stories, finder_options, results, benchmark.max_failures)
  Run at tools/telemetry/telemetry/internal/story_runner.py:218
    _RunStoryAndProcessErrorIfNeeded(story, results, state, test)
  _RunStoryAndProcessErrorIfNeeded at tools/.../story_runner.py:76
    state.WillRunStory(story)
  WillRunStory at tools/telemetry/.../page/shared_page_state.py:223
    self._StartBrowser(page)
  _StartBrowser at tools/.../telemetry/page/shared_page_state.py:169
    self._browser = self._possible_browser.Create(self._finder_options)
  Create at tools/.../backends/chrome/android_browser_finder.py:130
    raise original_exception
TypeError: __init__() takes at least 2 arguments (1 given)

This is incorrect, as I can see in the log that original_exception
was in fact a CommandTimeoutError. That is because re-raising
exc_info in this is not correct, at least if the exception
class doesn't have a zero-argument __init__. This exception class
does not, and the re-raise therefore fails to instantiate the class.

This patch rewrites the code using Python's standard re-raise
mechanism.

R=aiolos@chromium.org

Review URL: https://codereview.chromium.org/1377153002

Cr-Original-Commit-Position: refs/heads/master@{#359315}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 1840dda281c3c1388e2a8d47408bfbc40b0d71e1