Revert of Re-enable memory tests. Fixed sign-in issue. (patchset #3 of https://codereview.chromium.org/491863003/)
Reason for revert:
Failing on bots. Looks like we forgot to commit the archive.

Traceback (most recent call last):
  File "/b/build/slave/Android_Nexus5_Perf/build/src/tools/perf/../telemetry/telemetry/value/failure.py", line 39, in _GetExcInfoFromMessage
    raise Exception(message)
Exception: Page set archive doesn't exist.

http://chromegw/i/chromium.perf/builders/Android%20Nexus5%20Perf/builds/1480/steps/memory.mobile_memory/logs/stdio

Original issue's description:
> Re-enable memory tests. Fixed sign-in issue.
>
> Re-recording other tests may be required.
>
> BUG=370977
>
> Committed: https://chromium.googlesource.com/chromium/src/+/383ffaab6b5fac34b950d9faaab637cc75907aca

TBR=skyostil@chromium.org,starodub@google.com
NOTREECHECKS=true
NOTRY=true
BUG=370977

Review URL: https://codereview.chromium.org/511023002

Cr-Original-Commit-Position: refs/heads/master@{#292266}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a8ae96e7508f8fd8303dc4e2d5eb45615725763a