Re-add an explicit dependency on device_serial_mojo to battor agent.
This CL basically relands crrev.com/1511753004 - it somehow
got dropped via revert and reland of other CLs and I suspect
that this is what causes build failure below:
https://build.chromium.org/p/chromium/builders/Win/builds/38641/steps/compile/logs/stdio
c:\b\build\slave\win\build\src\tools\battor_agent\battor_connection.h(14) : fatal error C1083: Cannot open include file: 'device/serial/serial.mojom.h': No such file or directory

BUG=564667
TBR=charliea@chromium.org,nednguyen@chromium.org,mmenke@chromium.org,primiano@chromium.org,danakj@chromium.org,zhenw@chromium.org

Review URL: https://codereview.chromium.org/1542253003

Cr-Original-Commit-Position: refs/heads/master@{#366777}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2e53cb5448df90f11940a2e55ef6c74bd74ac3e7