Fix android build error with gcc 4.7.2.
Compiling the latest source tree with gcc 4.7.2 currently breaks at:

../../tools/android/forwarder2/socket.cc: In member function ‘int forwarder2::Socket::Read(void*, size_t)’:
../../tools/android/forwarder2/socket.cc:323:13: error: ‘read’ was not declared in this scope
../../tools/android/forwarder2/socket.cc:323:13: error: invalid type in declaration before ‘;’ token
[2269/11351] CXX obj/chrome/app/policy/gen...ettings_proto_compile.chrome_settings.pb.o
ninja: build stopped: subcommand failed.

It seems that 'tools/android/forwarder2/socket.cc' needs '#include <unistd.h>.

Review URL: https://chromiumcodereview.appspot.com/11896088

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 0e5c81fa046e2f9cb63204260068a73555e660b6