Revert of tools/battor_agent: Adds a tool to find connected BattOrs (patchset #3 id:40001 of https://codereview.chromium.org/1611533002/ )
Reason for revert:
buildbot failure in Chromium GPU on Android Debug (Nexus 6)

[918/3714] LINK battor_agent
...
obj/tools/battor_agent/libbattor_agent_lib.a(obj/tools/battor_agent/battor_agent_lib.battor_finder.o):battor_finder.cc:function battor::BattOrFinder::FindBattOr(): error: undefined reference to 'device::SerialDeviceEnumerator::Create()'

Original issue's description:
> tools/battor_agent: Adds a tool to find connected BattOrs
>
> This tool will also be used by the Chromium trace controller to find
> any connected BattOrs.
>
> BUG=542837
>
> Committed: https://crrev.com/22f5284d4b0e007cb59effaefa7dbd82717eca79
> Cr-Commit-Position: refs/heads/master@{#370985}

TBR=zhenw@chromium.org,nednguyen@google.com,sky@chromium.org,charliea@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=542837

Review URL: https://codereview.chromium.org/1623563002

Cr-Original-Commit-Position: refs/heads/master@{#370992}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 07fbdfb23f9b20157776fe37fb504de60f960dc2