Revert "[Autofill] Country/State rationalization."
This reverts commit 7df8da933e7d71de191ee15e24a5346a53fc37f1.

Reason for revert:
Doesn't build on iOS bots:
https://logs.chromium.org/v/?s=chromium%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8942978656263239232%2F%2B%2Fsteps%2Fcompile%2F0%2Fstdout
../../components/autofill/core/browser/form_structure.cc:1320:60: error: comparison of unsigned expression >= 0 is always true [-Werror,-Wtautological-compare]
  for (auto current_index = field_index - 1; current_index >= 0;
                                             ~~~~~~~~~~~~~ ^  ~

I filed https://bugs.chromium.org/p/chromium/issues/detail?id=855881 for
figuring out why the regular bots didn't catch this.

Original change's description:
> [Autofill] Country/State rationalization.
> 
> Sometimes, server misidentifies countries and states,
> and we can handle it with rationalization.
> This usually happens when the form/field signature of
> the two are identical. See go/rationalize-repeated-fields.
> 
> Tests + Refactoring.
> 
> Fixes: www.coolstuffinc.com
> Bug: 850220
> Change-Id: I85f601cd37f6c24b51423c8d3ccee0fc117f4f12
> Reviewed-on: https://chromium-review.googlesource.com/1099559
> Commit-Queue: Parastoo Geranmayeh <parastoog@google.com>
> Reviewed-by: Sebastien Seguin-Gagnon <sebsg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#569814}

TBR=sebsg@chromium.org,parastoog@google.com

Change-Id: If9433043e5fc735988bfa34c556267d36398b080
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 850220
Reviewed-on: https://chromium-review.googlesource.com/1112979
Reviewed-by: Nico Weber <thakis@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#569881}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b585fd98b3fcd3564c40b509cff3d33f75d81e33