Revert 182754 > Fixed browser crash when Telemetry uses Debug build. > > Factored out chrome.benchmarking methods which don't depend on stats table. > > > BUG=168640 > > TEST=tools/telemetry/run_tests --browser=debug PageRunnerTests > > Review URL: https://chromiumcodereview.appspot.com/11801024
Win7 perf bot throws error:
AttributeError: 'module' object has no attribute 'check_output

TBR=danhn@chromium.org
Review URL: https://codereview.chromium.org/12277013

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: cf80fa147602745859fd052c11bf770fc6c611f0