[Telemetry] Disable testPagesetRepeat on win.
It is failing and I suspect the problem is in the unittest not in the code
under test, so I'm disabling rather than reverting the other change.

File "E:\b\build\slave\XP_Tests__2_\build\src\tools\telemetry\telemetry\page\page_runner_unittest.py", line 240, in testPagesetRepeat
os.remove(output_file)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\docume~1\\chrome~2\\locals~1\\temp\\tmpiwpnmk'

TBR=dalecurtis@chromium.org
NOTRY=True
NOTREECHECKS=True
BUG=

Review URL: https://codereview.chromium.org/257983003

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2d8ed765f26369df9c7377434a8433cec8ad0df0