Display traceback after failing to load cfg.
Sample output:

Traceback (most recent call last):
  File "./tools/run-bisect-perf-regression.py", line 39, in LoadConfigFile
    local_vars)
  File "/usr/local/google/home/simonhatch/chromium/src/tools/run-bisect-perf-regression.cfg", line 64
    'truncate_percent':'',
                      ^
SyntaxError: invalid syntax

Error: Could not load config file. Double check your changes to run-bisect-perf-regression.cfg for syntax errors.


BUG=
NOTRY=true

Review URL: https://chromiumcodereview.appspot.com/16007011

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d6f9b9ef82e475dac6d61b6491d0eb52eb10dd72