Add missing <stdarg.h> include in generate_stubs.py
This is needed for va_list, va_start etc. This is breaking the
veyron_pinky Chrome OS build:

https://chromegw.corp.google.com/i/chromeos/builders/veyron_pinky%20chrome%20PFQ/builds/937/steps/BuildPackages/logs/stdio

chromeos-chrome-45.0.2433.0_rc-r1: obj/content/content_common.gen/v4l2_stubs.cc: In function 'int v4l2_ioctl(int, long unsigned int, ...)':
chromeos-chrome-45.0.2433.0_rc-r1: obj/content/content_common.gen/v4l2_stubs.cc:36:28: error: 'va_start' was not declared in this scope
chromeos-chrome-45.0.2433.0_rc-r1:    va_start(args___, request);
chromeos-chrome-45.0.2433.0_rc-r1:                             ^
chromeos-chrome-45.0.2433.0_rc-r1: obj/content/content_common.gen/v4l2_stubs.cc:37:60: error: expected primary-expression before 'void'
chromeos-chrome-45.0.2433.0_rc-r1:    LIBV4L_PUBLIC int ret___ = v4l2_ioctl_ptr(fd, request, va_arg(args___, void*));
chromeos-chrome-45.0.2433.0_rc-r1:                                                             ^
chromeos-chrome-45.0.2433.0_rc-r1: obj/content/content_common.gen/v4l2_stubs.cc:37:65: error: 'va_arg' was not declared in this scope
chromeos-chrome-45.0.2433.0_rc-r1:    LIBV4L_PUBLIC int ret___ = v4l2_ioctl_ptr(fd, request, va_arg(args___, void*));
chromeos-chrome-45.0.2433.0_rc-r1:                                                                  ^
chromeos-chrome-45.0.2433.0_rc-r1: obj/content/content_common.gen/v4l2_stubs.cc:38:17: error: 'va_end' was not declared in this scope
chromeos-chrome-45.0.2433.0_rc-r1:    va_end(args___);
chromeos-chrome-45.0.2433.0_rc-r1:                  ^

BUG=500800
TEST=cros chrome-sdk --board=veyron_pinky
  gclient runhooks
  ninja -C out_veyron_pinky/Release -j1000 -k50 chrome chrome_sandbox

Review URL: https://codereview.chromium.org/1188843002

Cr-Original-Commit-Position: refs/heads/master@{#334637}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 4f0fdc836a088dd6a3b05388f989e98c54540354