Remove trybot command.
This way of sending try jobs is deprecated. Print an error message and
redirect users to the docs on using Pinpoint.

Running with trybot will produce this message:

ERROR: This command has been removed.

Please visit https://chromium.googlesource.com/chromium/src/+/master/docs/speed/perf_trybots.md for up-to-date information on running perf try jobs.


Bug: 770009
Change-Id: I6c22aff02d76d56fad40b6fdaf167b16d22c3489
Reviewed-on: https://chromium-review.googlesource.com/874814
Commit-Queue: Simon Hatch <simonhatch@chromium.org>
Reviewed-by: Annie Sullivan <sullivan@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#530385}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 5d8ac50eb69e7ab99e0b476cb7bcfbe274671688