Modifications to skpicture_printer
* Changed the output directory option to '-s' and '--skp-outdir' because this was broken, running run_multipage_benchmarks with skpicture_printer resulted in the following error: 
optparse.OptionConflictError: option -o/--outdir: conflicting option string(s): -o 

* Added additional browser options due on recent changes in Skia/Chromium code base.

Review URL: https://chromiumcodereview.appspot.com/15665003

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: a1b5ca87c89db9adcb46cbe5b07a4ebfd7f4caea