Revert "Add policy descriptions for printing"
This reverts commit df15dab510cda02692e493598187d7eafc73a2c4.

Reason for revert: Breaks ChromeOS debug bot
https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/linux-chromeos-dbg
../../chrome/browser/policy/printing_restrictions_policy_handler.cc:12273: error: undefined reference to 'printing::GetAllowedColorModesForName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
../../chrome/browser/policy/printing_restrictions_policy_handler.cc:37320: error: undefined reference to 'printing::GetAllowedDuplexModesForName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'


Original change's description:
> Add policy descriptions for printing
> 
> This just adds new policy templates without implementation.
> 
> Bug: 853724
> Change-Id: Id2e0e9d0a3cbf353893fe96821e646dd0f5795a5
> Reviewed-on: https://chromium-review.googlesource.com/1155120
> Commit-Queue: Vladislav Kuzkokov <vkuzkokov@chromium.org>
> Reviewed-by: Pavol Marko <pmarko@chromium.org>
> Reviewed-by: Lei Zhang <thestig@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#586385}

TBR=thestig@chromium.org,vkuzkokov@chromium.org,pmarko@chromium.org

Change-Id: I74492046a844affd91e3c4e4dae3108c97ad8626
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 853724
Reviewed-on: https://chromium-review.googlesource.com/1192136
Reviewed-by: John Abd-El-Malek <jam@chromium.org>
Commit-Queue: John Abd-El-Malek <jam@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#586426}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: c78f01d6175693f1aa36049c0755756dbdfcf8ec