Fix type error class_methods.py
This line currently causes my gdb sessions to error out with:

  TypeError: unorderable types: list() > int()

Looks like this just wants to check for an empty list

Bug: None
Change-Id: I5de214c2373045a320e83db229b2ae449b78c967
Reviewed-on: https://chromium-review.googlesource.com/c/1352645
Reviewed-by: Robert Flack <flackr@chromium.org>
Reviewed-by: Jeremy Roman <jbroman@chromium.org>
Commit-Queue: Jeremy Roman <jbroman@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#611488}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 502291e49e07882375c4bff16e5c1aac2427cd02