Revert of Move base_dir to user_story_set, remove file_path. (patchset #4 id:60001 of https://codereview.chromium.org/946473002/)
Reason for revert:
breaks on main waterfall, i.e.
http://build.chromium.org/p/chromium.win/builders/Win%207%20Tests%20x64%20%281%29/builds/21577/steps/telemetry_unittests/logs/stdio

  AssertionError: 'E:\\b\\build\\slave\\Win_7_Tests_x64__1_\\build\\src\\tools\\telemetry\\telemetry\\user_story\\user_story_set_unittest.pyc' != 'E:\\b\\build\\slave\\Win_7_Tests_x64__1_\\build\\src\\tools\\telemetry\\telemetry\\user_story\\user_story_set_unittest.py'

not sure why this fails on main waterfall but not trybots?

Original issue's description:
> Move base_dir to user_story_set, remove file_path.
>
> BUG=454531
>
> Committed: https://crrev.com/65ff7d22f8986ab2832045af09160dc753e40c5f
> Cr-Commit-Position: refs/heads/master@{#317632}

TBR=chrishenry@google.com,dtu@chromium.org,sullivan@chromium.org,nednguyen@google.com,aiolos@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=454531

Review URL: https://codereview.chromium.org/951593003

Cr-Original-Commit-Position: refs/heads/master@{#317665}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 14042b4980d2bcf8c2a070ebdfde646626990d23