[Telemetry] Add two missing methods to ios browser finder.
Fixes:
  AttributeError: 'module' object has no attribute 'SelectDefaultBrowser'

BUG=

Review URL: https://codereview.chromium.org/355513002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e081341883a2140276703bb36e392fa2d1575809