Revert 267095 "Remove WebUI NTP on Android."
It may have caused Android Builder to fail:
http://build.chromium.org/p/chromium.webkit/builders/Android%20Builder/builds/38786/steps/compile/logs/stdio
http://build.chromium.org/p/chromium.linux/builders/Android%20Builder%20%28dbg%29/builds/56685/steps/compile/logs/stdio

"error: undefined reference to 'NTPUserDataLogger::GetOrCreateFromWebContents(content::WebContents*)'" etc.

> Remove WebUI NTP on Android.
> 
> Chrome for Android has transitioned to using native NTP. This CL removes
> the WebUI classes and resources.
> 
> BUG=284770
> 
> Review URL: https://codereview.chromium.org/256763004

TBR=aurimas@chromium.org

Review URL: https://codereview.chromium.org/264543002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fc6535a4438bf843317b4eec31b6ffcdfe4d8ccf