Revert of [telemetry] Refactor run_tests to remove old cruft. (https://codereview.chromium.org/228073002/)
Reason for revert:
Causing builder failures, eg:
http://build.chromium.org/p/chromiumos.chromium/builders/AMD64%20%28chromium%29/builds/333

Error is missing gtest_testrunner module, removed in this CL:

ERROR:root:selenium module failed to be imported.
autotest-chrome-0.0.1-r3848: ERROR:root:telemetry_UnitTests import error: cannot import name gtest_testrunner.  Skipping telemetry_UnitTests
autotest-chrome-0.0.1-r3848: Traceback (most recent call last):
autotest-chrome-0.0.1-r3848:   File "/build/amd64-generic/tmp/portage/chromeos-base/autotest-chrome-0.0.1-r3848/work/autotest-work/client/bin/setup_job.py", line 72, in init_test
autotest-chrome-0.0.1-r3848:     exec import_stmt + '\n' + init_stmt in locals_dict, globals_dict
autotest-chrome-0.0.1-r3848:   File "<string>", line 1, in <module>
autotest-chrome-0.0.1-r3848:   File "/build/amd64-generic/tmp/portage/chromeos-base/autotest-chrome-0.0.1-r3848/work/autotest-work/client/site_tests/telemetry_UnitTests/telemetry_UnitTests.py", line 7, in <module>
autotest-chrome-0.0.1-r3848:     from telemetry.unittest import gtest_testrunner, run_tests
autotest-chrome-0.0.1-r3848: ImportError: cannot import name gtest_testrunner

TBR=nduca, tonyg, Ken Russell, dtu
NOTRY=true
NOTREECHECKS=true
BUG=346956

Original issue's description:
> [telemetry] Refactor run_tests to remove old cruft.
> 
> - Remove dead code and circuitous code paths.
> - Make its API consistent with run_benchmark, taking advantage of command_line.OptparseCommand.
> 
> 
> BUG=346956
> TEST=tools/telemetry/run_tests && tools/perf/run_tests
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=280232

Review URL: https://codereview.chromium.org/355203002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 83dd150d2fdd0bdf3d66e1e1e7244a47cd7e340f