Telemetry / Android: do not crash on GetCpuStats() if the process is gone.
Some bots are failing with:
...[0].split()
IndexError: list index out of range
This can specially happen on page cyclers,
since multiple renders can be started and killed by the
framework.

BUG=

Review URL: https://codereview.chromium.org/25002005

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 317caf49898fcc6bd3024b7627da535b9b157ab7