[Cronet] Use gn desc to find third party licenses on Android.
Filter out build/secondary/third_party dependencies to work around
__main__.LicenseError: missing README.chromium or licenses.py SPECIAL_CASES entry in build/secondary/third_party/android_tools

BUG=606859
BUG=710801
CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.android:android_cronet_tester

Review-Url: https://codereview.chromium.org/2959303002
Cr-Original-Commit-Position: refs/heads/master@{#485291}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 0fd5121f8fe912464b4f4d46dbb90d6209f59bf0