Revert of Remove LSan options/suppressions from test_env.py. (patchset #1 id:1 of https://codereview.chromium.org/940033002/)
Reason for revert:
Breaks Linux ASAN:

https://build.chromium.org/p/chromium.memory/builders/Linux%20ASan%20LSan%20Builder/builds/19163/steps/isolate%20tests/logs/stdio

The error is:

MappingError: Input file /mnt/data/b/build/slave/Linux_ASan_LSan_Builder/build/src/tools/lsan/suppressions.txt doesn't exist

Original issue's description:
> Remove LSan options/suppressions from test_env.py.
>
> Those are now compiled into the executable.
> Also remove tools/lsan/ which used to house the suppressions file.
>
> BUG=302040
> R=kjellander@chromium.org
>
> Committed: https://crrev.com/09fef383665c6d75776bb0b649b29685b38ce617
> Cr-Commit-Position: refs/heads/master@{#318035}

TBR=kjellander@chromium.org,earthdok@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=302040

Review URL: https://codereview.chromium.org/956603004

Cr-Original-Commit-Position: refs/heads/master@{#318043}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 207c1a328efe47f10bb0fb41411936051b2bf062