Fix bug in mass_rename
This fixes a bug where moving a file, but not renaming it resulted in an exception:

Traceback (most recent call last):
  File "/secondary/builds/build2/src/tools/git/move_source_file.py", line 259, in <module>
    sys.exit(main())
  File "/secondary/builds/build2/src/tools/git/move_source_file.py", line 254, in main
    UpdatePostMove(from_path, to_path, in_blink)
  File "/secondary/builds/build2/src/tools/git/move_source_file.py", line 172, in UpdatePostMove
    os.path.join(visiting_directory, '*.gyp*')])
  File "/secondary/builds/build2/src/tools/git/mffr.py", line 69, in MultiFileFindReplace
    referee)
Exception: No change in file mojo/common/BUILD.gn although matched in grep
Traceback (most recent call last):
  File "/secondary/builds/build2/src/tools/git/mass-rename.py", line 50, in <module>
    sys.exit(main())
  File "/secondary/builds/build2/src/tools/git/mass-rename.py", line 43, in main
    fro, to])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/secondary/builds/build2/src/tools/git/move_source_file.py', '--already_moved', '--no_error_for_non_so\
urce_file', 'mojo/common/handle_watcher.h', 'mojo/message_pump/handle_watcher.h']' returned non-zero exit status 1

BUG=none
TEST=none
R=mgiuca@chromium.org, satorux@chromium.org

Review URL: https://codereview.chromium.org/1265313002

Cr-Original-Commit-Position: refs/heads/master@{#342030}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 81d49526d67b9a8c8de98abd44540d917333de36