Revert of Start recording IO thread tasks as well as main thread tasks (patchset #12 id:210001 of https://codereview.chromium.org/750123003/)
Reason for revert:
Causes test failures on two bots:
http://build.chromium.org/p/chromium.linux/builders/Linux%20Tests%20%28dbg%29%281%29/builds/37369
http://build.chromium.org/p/chromium.mac/builders/Mac10.9%20Tests%20%28dbg%29/builds/1731

[1/1] measurements.task_execution_time_unittest.TaskExecutionTimeUnitTest.testSlicesConformToRequiredNamingConventionsUsingDummyPage failed unexpectedly:
  Unable to find file in Cloud Storage: /mnt/data/b/build/slave/Linux_Tests__dbg__1_/build/src/tools/telemetry/unittest_data/test_000.wpr
  Could not find Flash at /mnt/data/b/build/slave/Linux_Tests__dbg__1_/build/src/third_party/adobe/flash/binaries/ppapi/linux/libpepflashplayer.so. Continuing without Flash.
  To run with Flash, check it out via http://go/read-src-internal
  Traceback (most recent call last):
    File "/mnt/data/b/build/slave/Linux_Tests__dbg__1_/build/src/tools/telemetry/telemetry/decorators.py", line 55, in wrapper
      func(*args, **kwargs)
    File "/mnt/data/b/build/slave/Linux_Tests__dbg__1_/build/src/tools/perf/measurements/task_execution_time_unittest.py", line 75, in testSlicesConformToRequiredNamingConventionsUsingDummyPage
      self.assertGreater(use_counts, 0)
  AssertionError: 0 not greater than 0

Original issue's description:
> Start recording IO thread tasks as well as main thread tasks.
>
> Recently a new metric "task_execution_time" was added. This reports the top 10 slowest tasks on the main renderer thread. With this update task_execution_time is extended to additionally report the top 10 slowest tasks on the browser and renderer IO threads.
>
> BUG=421434
>
> Committed: https://crrev.com/e70bc338dfa4eb6e25d0491275c54d3efdc6332b
> Cr-Commit-Position: refs/heads/master@{#310482}

TBR=skyostil@google.com,alexclarke@google.com,petrcermak@google.com,ssid@google.com,rmcilroy@google.com,skyostil@chromium.org,petrcermak@chromium.org,rmcilroy@chromium.org,tonyg@chromium.org,picksi@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=421434

Review URL: https://codereview.chromium.org/784273008

Cr-Original-Commit-Position: refs/heads/master@{#310518}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 96f142a3652ea5144c1da97fa50cdc3e49f26ce0