Fix narrowing warning in battor_sample_converter_unittest
On VS2015:

d:\src\cr3\src\tools\battor_agent\battor_sample_converter_unittest.cc(28): error C2397: conversion from 'double' to 'int16_t' requires a narrowing conversion

R=brucedawson@chromium.org, charliea@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1648123002

Cr-Original-Commit-Position: refs/heads/master@{#372227}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 5911df8c175be2371f8907018a8c673120581912