Revert 279958 "Revert "Revert 279650 "Add VaapiVideoEncodeAccele..."
This once again broke the cros_x86 builder. I think you want the Range to be static_cast<size_t> not static_cast<uint32>.

http://build.chromium.org/p/chromiumos.chromium/builders/X86%20%28chromium%29/builds/333

chromeos-chrome-38.0.2071.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/media/filters/h264_bitstream_buffer_unittest.cc:52:226: error: could not convert 'testing::Range(T, T) [with T = long long unsigned int](65ull)' from 'testing::internal::ParamGenerator<long long unsigned int>' to 'testing::internal::ParamGenerator<unsigned int>'
chromeos-chrome-38.0.2071.0_alpha-r1:  INSTANTIATE_TEST_CASE_P(AppendNumBits,


> Revert "Revert 279650 "Add VaapiVideoEncodeAccelerator for HW-accelerate...""
> 
> Fixing the cros_trunk builder compilation failure in
> h264_bitstream_buffer_unittest, for which this was reverted.
> 
> > Revert 279650 "Add VaapiVideoEncodeAccelerator for HW-accelerate..."
> >
> > Broke the Chrome-on-Chrome OS compile
> >
> > http://master.chrome.corp.google.com:8011/builders/cros%20trunk/builds/21417
> >
> > > Add VaapiVideoEncodeAccelerator for HW-accelerated video encode.
> > >
> > > Add an implementation of VideoEncodeAccelerator utilizing VA-API for
> > > hardware encode on Intel-based ChromeOS platforms.
> > >
> > > BUG=378962
> > > TEST=video_encode_accelerator_unittest
> > >
> > > Review URL: https://codereview.chromium.org/333253002
> >
> > TBR=posciak@chromium.org
> >
> > Review URL: https://codereview.chromium.org/350413002
> >
> > git-svn-id: svn://svn.chromium.org/chrome/trunk/src@279733 0039d316-1c4b-4281-b951-d872f2087c98
> 
> TBR=jamescook@chromium.org
> BUG=388778,378962
> 
> Review URL: https://codereview.chromium.org/356903002

TBR=posciak@chromium.org

Review URL: https://codereview.chromium.org/357903003

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d0d5018b2f5aa82ef8a57987b66028e9096190ad