Revert "Report data usage UMA for Chrome services"
This reverts commit aa789c8328a65922859dfd8ca2d9b18212dc3c94.

Broken compile:
../../sync/tools/sync_client.cc:408:32: error: too few arguments to
function call, expected 2, have 1
  post_factory->Init(kUserAgent);
    ~~~~~~~~~~~~~~~~~~           ^

BUG=527304

Review URL: https://codereview.chromium.org/1339943003 .

Cr-Original-Commit-Position: refs/heads/master@{#348564}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 294165fa24917221f3738f5ef5707f3bf4b25678